/*
  HR System — PostgreSQL schema (Supabase / managed PG 14+)
  Encoding: UTF-8

  خطوات جاهزة (انسخ والصق):
    1) Supabase → SQL Editor → لصق هذا الملف كاملاً → Run.
    2) Supabase → Settings → Database → انسخ Connection string (URI).
    3) انسخ backend/database/supabase.env.example إلى backend/.env واملأ DATABASE_URL و JWT_*.
    4) في مجلد backend: npm install ثم npm run start

  تفاصيل إضافية: backend/database/SUPABASE-SETUP.txt

  Notes:
    - Mirrors Sequelize models (underscored columns, snake_case tables).
    - updated_at is set by the application (not DB triggers).
    - users.company_id may be NULL for super-admin accounts.
*/

SET client_encoding = 'UTF8';

-- ── Tear down (dependency order) ───────────────────────────────────────────
DROP TABLE IF EXISTS device_logs CASCADE;
DROP TABLE IF EXISTS surprise_attendance_events CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS payroll_item_components CASCADE;
DROP TABLE IF EXISTS payroll_items CASCADE;
DROP TABLE IF EXISTS payroll_runs CASCADE;
DROP TABLE IF EXISTS employee_salary_components CASCADE;
DROP TABLE IF EXISTS salary_components CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS leave_balances CASCADE;
DROP TABLE IF EXISTS leave_types CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS attendance_requests CASCADE;
DROP TABLE IF EXISTS employee_documents CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS work_shifts CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS company_features CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS companies CASCADE;

-- ── Optional: enum types (drop if re-run) ────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE gender_t AS ENUM ('MALE','FEMALE','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE marital_t AS ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE contract_type_t AS ENUM ('FULL_TIME','PART_TIME','CONTRACT','INTERN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE emp_status_t AS ENUM ('ACTIVE','INACTIVE','TERMINATED','ON_LEAVE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE att_status_t AS ENUM ('PRESENT','ABSENT','LATE','HALF_DAY','HOLIDAY','WEEKEND','ON_LEAVE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE att_source_t AS ENUM ('MANUAL','DEVICE','IMPORT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE leave_req_status_t AS ENUM ('PENDING','APPROVED','REJECTED','CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE gender_specific_t AS ENUM ('ALL','MALE','FEMALE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE salary_comp_type_t AS ENUM ('ADDITION','DEDUCTION');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE payroll_run_status_t AS ENUM ('DRAFT','PROCESSING','APPROVED','PAID','CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE pic_source_t AS ENUM ('COMPONENT','AUTO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE device_type_t AS ENUM ('FINGERPRINT','CARD','FACE','PIN','HYBRID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE device_mode_t AS ENUM ('ATTENDANCE','VERIFY_ONLY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE device_status_t AS ENUM ('ACTIVE','INACTIVE','OFFLINE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE device_event_t AS ENUM ('CHECK_IN','CHECK_OUT','VERIFY','ALARM','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 1. companies ────────────────────────────────────────────────────────────
CREATE TABLE companies (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(200)    NOT NULL,
  name_ar          VARCHAR(200)    NOT NULL DEFAULT '',
  logo             VARCHAR(500)    NULL,
  phone            VARCHAR(30)     NULL,
  email            VARCHAR(150)    NULL,
  address          TEXT            NULL,
  tax_id           VARCHAR(50)     NULL,
  currency         VARCHAR(10)     NOT NULL DEFAULT 'IQD',
  timezone         VARCHAR(50)     NOT NULL DEFAULT 'Asia/Baghdad',
  is_active        SMALLINT        NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  contract_start   DATE            NULL,
  contract_end     DATE            NULL,
  contract_doc     VARCHAR(500)    NULL,
  login_password_hash VARCHAR(255) NULL,
  created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_companies_is_active ON companies (is_active);

-- ── 2. roles ────────────────────────────────────────────────────────────────
CREATE TABLE roles (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  name            VARCHAR(80)  NOT NULL,
  name_ar         VARCHAR(80)  NOT NULL DEFAULT '',
  permissions     JSONB        NULL,
  is_system       SMALLINT     NOT NULL DEFAULT 0 CHECK (is_system IN (0,1)),
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_roles_company_name UNIQUE (company_id, name)
);

CREATE INDEX idx_roles_company_id ON roles (company_id);

-- ── 3. departments ───────────────────────────────────────────────────────────
CREATE TABLE departments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  name            VARCHAR(120) NOT NULL,
  name_ar         VARCHAR(120) NOT NULL DEFAULT '',
  parent_id       INTEGER NULL REFERENCES departments (id) ON DELETE SET NULL,
  manager_id      INTEGER NULL,
  is_active       SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_departments_company_id ON departments (company_id);
CREATE INDEX idx_departments_parent_id  ON departments (parent_id);
CREATE INDEX idx_departments_manager_id ON departments (manager_id);

-- ── 4. positions ───────────────────────────────────────────────────────────
CREATE TABLE positions (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  department_id   INTEGER NULL REFERENCES departments (id) ON DELETE SET NULL,
  title           VARCHAR(120) NOT NULL,
  title_ar        VARCHAR(120) NOT NULL DEFAULT '',
  grade           VARCHAR(20)  NULL,
  is_active       SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_positions_company_id    ON positions (company_id);
CREATE INDEX idx_positions_department_id ON positions (department_id);

-- ── 5. work_shifts ──────────────────────────────────────────────────────────
CREATE TABLE work_shifts (
  id                           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id                   INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  name                         VARCHAR(80)  NOT NULL,
  name_ar                      VARCHAR(80)  NOT NULL DEFAULT '',
  shift_start                  TIME NOT NULL,
  shift_end                    TIME NOT NULL,
  standard_hours               NUMERIC(4,2) NOT NULL DEFAULT 8.00,
  grace_minutes                SMALLINT NOT NULL DEFAULT 0,
  overtime_threshold_minutes   SMALLINT NOT NULL DEFAULT 0,
  is_default                   SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)),
  is_active                    SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  break_start                  TIME NULL,
  break_end                    TIME NULL,
  checkin_window_start         TIME NULL,
  checkin_window_end           TIME NULL,
  checkout_window_start        TIME NULL,
  checkout_window_end          TIME NULL,
  work_days                    JSONB NULL,
  week_starts_on               SMALLINT NOT NULL DEFAULT 6,
  holidays                     JSONB NULL,
  created_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_ws_company         ON work_shifts (company_id);
CREATE INDEX idx_ws_company_default ON work_shifts (company_id, is_default);
CREATE INDEX idx_ws_active          ON work_shifts (is_active);

-- ── 6. employees ─────────────────────────────────────────────────────────────
CREATE TABLE employees (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_number     VARCHAR(30)  NOT NULL,
  first_name          VARCHAR(80)  NOT NULL,
  last_name           VARCHAR(80)  NOT NULL,
  first_name_ar       VARCHAR(80)  NOT NULL DEFAULT '',
  last_name_ar        VARCHAR(80)  NOT NULL DEFAULT '',
  gender              gender_t NOT NULL DEFAULT 'MALE',
  birth_date          DATE NULL,
  national_id         VARCHAR(30)  NULL,
  nationality         VARCHAR(60)  NULL,
  marital_status      marital_t NULL,
  phone               VARCHAR(30)  NULL,
  email               VARCHAR(150) NULL,
  address             TEXT NULL,
  photo               VARCHAR(500) NULL,
  hire_date           DATE NOT NULL,
  termination_date    DATE NULL,
  contract_type       contract_type_t NOT NULL DEFAULT 'FULL_TIME',
  status              emp_status_t NOT NULL DEFAULT 'ACTIVE',
  department_id       INTEGER NULL REFERENCES departments (id) ON DELETE SET NULL,
  position_id         INTEGER NULL REFERENCES positions (id) ON DELETE SET NULL,
  manager_id          INTEGER NULL REFERENCES employees (id) ON DELETE SET NULL,
  shift_id            INTEGER NULL REFERENCES work_shifts (id) ON DELETE SET NULL,
  bank_name           VARCHAR(100) NULL,
  bank_account        VARCHAR(60)  NULL,
  iban                VARCHAR(34)  NULL,
  base_salary         NUMERIC(12,2) NOT NULL DEFAULT 0,
  deleted_at          TIMESTAMP WITHOUT TIME ZONE NULL,
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_employees_number UNIQUE (company_id, employee_number)
);

CREATE UNIQUE INDEX uq_employees_national ON employees (company_id, national_id) WHERE national_id IS NOT NULL;
CREATE INDEX idx_employees_company_id    ON employees (company_id);
CREATE INDEX idx_employees_department_id ON employees (department_id);
CREATE INDEX idx_employees_position_id   ON employees (position_id);
CREATE INDEX idx_employees_manager_id    ON employees (manager_id);
CREATE INDEX idx_employees_shift_id      ON employees (shift_id);
CREATE INDEX idx_employees_status        ON employees (status);
CREATE INDEX idx_employees_hire_date     ON employees (hire_date);
CREATE INDEX idx_employees_deleted_at    ON employees (deleted_at);

ALTER TABLE departments
  ADD CONSTRAINT fk_dept_manager
  FOREIGN KEY (manager_id) REFERENCES employees (id) ON DELETE SET NULL;

-- ── 7. users ────────────────────────────────────────────────────────────────
CREATE TABLE users (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id     INTEGER NULL REFERENCES employees (id) ON DELETE SET NULL,
  role_id         INTEGER NOT NULL REFERENCES roles (id),
  email           VARCHAR(150) NOT NULL,
  password_hash   VARCHAR(255) NOT NULL,
  is_active       SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  last_login      TIMESTAMP WITHOUT TIME ZONE NULL,
  refresh_token   VARCHAR(512) NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE UNIQUE INDEX uq_users_email_tenant ON users (company_id, email) WHERE company_id IS NOT NULL;
CREATE UNIQUE INDEX uq_users_email_super  ON users (email) WHERE company_id IS NULL;
CREATE INDEX idx_users_company_id  ON users (company_id);
CREATE INDEX idx_users_employee_id ON users (employee_id);
CREATE INDEX idx_users_role_id     ON users (role_id);
CREATE INDEX idx_users_is_active   ON users (is_active);

-- ── 8. company_features ─────────────────────────────────────────────────────
CREATE TABLE company_features (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  feature_key  VARCHAR(60) NOT NULL,
  is_enabled   SMALLINT NOT NULL DEFAULT 1 CHECK (is_enabled IN (0,1)),
  CONSTRAINT uq_company_feature UNIQUE (company_id, feature_key)
);

CREATE INDEX idx_company_features_company_id ON company_features (company_id);

-- ── 9. employee_documents ─────────────────────────────────────────────────────
CREATE TABLE employee_documents (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id     INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  doc_type        VARCHAR(60)  NOT NULL,
  title           VARCHAR(200) NOT NULL,
  file_path       VARCHAR(500) NOT NULL,
  expiry_date     DATE NULL,
  notes           TEXT NULL,
  uploaded_by     INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_edocs_company_id  ON employee_documents (company_id);
CREATE INDEX idx_edocs_employee_id ON employee_documents (employee_id);
CREATE INDEX idx_edocs_doc_type    ON employee_documents (doc_type);
CREATE INDEX idx_edocs_expiry_date ON employee_documents (expiry_date);

-- ── 10. attendance ───────────────────────────────────────────────────────────
CREATE TABLE attendance (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id         INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  work_date           DATE NOT NULL,
  check_in            TIMESTAMP WITHOUT TIME ZONE NULL,
  check_out           TIMESTAMP WITHOUT TIME ZONE NULL,
  total_minutes       SMALLINT NULL,
  overtime_minutes    SMALLINT NOT NULL DEFAULT 0,
  late_minutes        SMALLINT NOT NULL DEFAULT 0,
  status              att_status_t NOT NULL DEFAULT 'PRESENT',
  is_surprise         SMALLINT NOT NULL DEFAULT 0 CHECK (is_surprise IN (0,1)),
  surprise_event_id   INTEGER NULL,
  surprise_punch_time TIMESTAMP WITHOUT TIME ZONE NULL,
  source              att_source_t NOT NULL DEFAULT 'MANUAL',
  notes               TEXT NULL,
  created_by          INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_attendance_emp_date UNIQUE (company_id, employee_id, work_date)
);

CREATE INDEX idx_attendance_company_id  ON attendance (company_id);
CREATE INDEX idx_attendance_employee_id ON attendance (employee_id);
CREATE INDEX idx_attendance_work_date   ON attendance (work_date);
CREATE INDEX idx_attendance_status      ON attendance (status);
CREATE INDEX idx_attendance_is_surprise ON attendance (is_surprise);

-- ── 10b. attendance_requests (GPS / photo check-in requests) ─────────────────
CREATE TABLE attendance_requests (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id       INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id      INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  request_type     VARCHAR(20)  NOT NULL,
  request_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  work_date        DATE NOT NULL,
  gps_latitude     NUMERIC(10, 7) NOT NULL,
  gps_longitude    NUMERIC(10, 7) NOT NULL,
  gps_accuracy_m   NUMERIC(8, 2) NOT NULL DEFAULT 0,
  photo_path       VARCHAR(255) NOT NULL,
  note             TEXT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  reviewed_by      INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  reviewed_at      TIMESTAMP WITHOUT TIME ZONE NULL,
  rejection_reason TEXT NULL,
  created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_ar_company_id  ON attendance_requests (company_id);
CREATE INDEX idx_ar_employee_id ON attendance_requests (employee_id);
CREATE INDEX idx_ar_status      ON attendance_requests (status);
CREATE INDEX idx_ar_work_date   ON attendance_requests (work_date);

-- ── 11. leave_types ──────────────────────────────────────────────────────────
CREATE TABLE leave_types (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  name                VARCHAR(100) NOT NULL,
  name_ar             VARCHAR(100) NOT NULL DEFAULT '',
  max_days_per_year   SMALLINT NOT NULL DEFAULT 0,
  is_paid             SMALLINT NOT NULL DEFAULT 1 CHECK (is_paid IN (0,1)),
  carry_forward       SMALLINT NOT NULL DEFAULT 0 CHECK (carry_forward IN (0,1)),
  max_carry_days      SMALLINT NOT NULL DEFAULT 0,
  requires_approval   SMALLINT NOT NULL DEFAULT 1 CHECK (requires_approval IN (0,1)),
  gender_specific     gender_specific_t NOT NULL DEFAULT 'ALL',
  is_active           SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_leave_types_company_id ON leave_types (company_id);
CREATE INDEX idx_leave_types_is_active  ON leave_types (is_active);

-- ── 12. leave_balances ───────────────────────────────────────────────────────
CREATE TABLE leave_balances (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id       INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id      INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  leave_type_id    INTEGER NOT NULL REFERENCES leave_types (id) ON DELETE CASCADE,
  year             SMALLINT NOT NULL,
  total_days       NUMERIC(6,1) NOT NULL DEFAULT 0,
  used_days        NUMERIC(6,1) NOT NULL DEFAULT 0,
  pending_days     NUMERIC(6,1) NOT NULL DEFAULT 0,
  remaining_days   NUMERIC(6,1) GENERATED ALWAYS AS (total_days - used_days - pending_days) STORED,
  updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_leave_balances UNIQUE (company_id, employee_id, leave_type_id, year)
);

CREATE INDEX idx_lb_company_id  ON leave_balances (company_id);
CREATE INDEX idx_lb_employee_id ON leave_balances (employee_id);
CREATE INDEX idx_lb_year        ON leave_balances (year);

-- ── 13. leave_requests ───────────────────────────────────────────────────────
CREATE TABLE leave_requests (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id         INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  leave_type_id       INTEGER NOT NULL REFERENCES leave_types (id),
  start_date          DATE NOT NULL,
  end_date            DATE NOT NULL,
  total_days          NUMERIC(6,1) NOT NULL DEFAULT 1,
  reason              TEXT NULL,
  status              leave_req_status_t NOT NULL DEFAULT 'PENDING',
  approved_by         INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  approved_at         TIMESTAMP WITHOUT TIME ZONE NULL,
  rejection_reason    TEXT NULL,
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_lr_company_id    ON leave_requests (company_id);
CREATE INDEX idx_lr_employee_id   ON leave_requests (employee_id);
CREATE INDEX idx_lr_leave_type_id ON leave_requests (leave_type_id);
CREATE INDEX idx_lr_status        ON leave_requests (status);

-- ── 14. salary_components ──────────────────────────────────────────────────────
CREATE TABLE salary_components (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  name            VARCHAR(100) NOT NULL,
  name_ar         VARCHAR(100) NOT NULL DEFAULT '',
  type            salary_comp_type_t NOT NULL,
  is_percentage   SMALLINT NOT NULL DEFAULT 0 CHECK (is_percentage IN (0,1)),
  value           NUMERIC(10,4) NOT NULL DEFAULT 0,
  is_taxable      SMALLINT NOT NULL DEFAULT 0 CHECK (is_taxable IN (0,1)),
  applies_to_all  SMALLINT NOT NULL DEFAULT 1 CHECK (applies_to_all IN (0,1)),
  is_active       SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_sc_company_id ON salary_components (company_id);
CREATE INDEX idx_sc_type       ON salary_components (type);

-- ── 15. employee_salary_components ─────────────────────────────────────────────
CREATE TABLE employee_salary_components (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  employee_id     INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  component_id    INTEGER NOT NULL REFERENCES salary_components (id) ON DELETE CASCADE,
  override_value  NUMERIC(10,4) NULL,
  effective_from  DATE NOT NULL,
  effective_to    DATE NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_esc_company_id   ON employee_salary_components (company_id);
CREATE INDEX idx_esc_employee_id  ON employee_salary_components (employee_id);
CREATE INDEX idx_esc_component_id ON employee_salary_components (component_id);

-- ── 16. payroll_runs ──────────────────────────────────────────────────────────
CREATE TABLE payroll_runs (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  run_month           SMALLINT NOT NULL,
  run_year            SMALLINT NOT NULL,
  status              payroll_run_status_t NOT NULL DEFAULT 'DRAFT',
  total_employees     INTEGER NOT NULL DEFAULT 0,
  total_gross         NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_deductions    NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_net           NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes               TEXT NULL,
  processed_by        INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  processed_at        TIMESTAMP WITHOUT TIME ZONE NULL,
  approved_by         INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  approved_at         TIMESTAMP WITHOUT TIME ZONE NULL,
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_payroll_runs UNIQUE (company_id, run_month, run_year)
);

CREATE INDEX idx_pr_company_id ON payroll_runs (company_id);
CREATE INDEX idx_pr_status     ON payroll_runs (status);

-- ── 17. payroll_items ─────────────────────────────────────────────────────────
CREATE TABLE payroll_items (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  payroll_run_id      INTEGER NOT NULL REFERENCES payroll_runs (id) ON DELETE CASCADE,
  employee_id         INTEGER NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  working_days        SMALLINT NOT NULL DEFAULT 30,
  actual_days         NUMERIC(5,1) NOT NULL DEFAULT 0,
  absent_days         NUMERIC(5,1) NOT NULL DEFAULT 0,
  paid_leave_days     NUMERIC(5,1) NOT NULL DEFAULT 0,
  unpaid_leave_days   NUMERIC(5,1) NOT NULL DEFAULT 0,
  overtime_minutes    INTEGER NOT NULL DEFAULT 0,
  late_minutes        INTEGER NOT NULL DEFAULT 0,
  leave_days          NUMERIC(5,1) NOT NULL DEFAULT 0,
  base_salary         NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_additions     NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_deductions    NUMERIC(12,2) NOT NULL DEFAULT 0,
  gross_salary        NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_salary          NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes               TEXT NULL,
  created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_payroll_items UNIQUE (company_id, payroll_run_id, employee_id)
);

CREATE INDEX idx_pi_company_id  ON payroll_items (company_id);
CREATE INDEX idx_pi_run_id      ON payroll_items (payroll_run_id);
CREATE INDEX idx_pi_employee_id ON payroll_items (employee_id);

-- ── 18. payroll_item_components ───────────────────────────────────────────────
CREATE TABLE payroll_item_components (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  payroll_item_id INTEGER NOT NULL REFERENCES payroll_items (id) ON DELETE CASCADE,
  component_id    INTEGER NULL REFERENCES salary_components (id) ON DELETE SET NULL,
  component_name  VARCHAR(100) NOT NULL,
  type            salary_comp_type_t NOT NULL,
  amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
  source          pic_source_t NOT NULL DEFAULT 'COMPONENT',
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_pic_company_id      ON payroll_item_components (company_id);
CREATE INDEX idx_pic_payroll_item_id ON payroll_item_components (payroll_item_id);
CREATE INDEX idx_pic_component_id    ON payroll_item_components (component_id);

-- ── 19. announcements ───────────────────────────────────────────────────────
CREATE TABLE announcements (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  title           VARCHAR(200) NOT NULL,
  title_ar        VARCHAR(200) NOT NULL DEFAULT '',
  body            TEXT NOT NULL,
  body_ar         TEXT NOT NULL DEFAULT '',
  target_role_id  INTEGER NULL REFERENCES roles (id) ON DELETE SET NULL,
  published_by    INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  published_at    TIMESTAMP WITHOUT TIME ZONE NULL,
  expires_at      TIMESTAMP WITHOUT TIME ZONE NULL,
  is_pinned       SMALLINT NOT NULL DEFAULT 0 CHECK (is_pinned IN (0,1)),
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_ann_company_id   ON announcements (company_id);
CREATE INDEX idx_ann_published_at ON announcements (published_at);

-- ── 20. audit_logs ────────────────────────────────────────────────────────────
CREATE TABLE audit_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  user_id         INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  action          VARCHAR(50)  NOT NULL,
  table_name      VARCHAR(80)  NOT NULL,
  record_id       INTEGER NULL,
  old_values      JSONB NULL,
  new_values      JSONB NULL,
  ip_address      VARCHAR(45)  NULL,
  user_agent      VARCHAR(255) NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_audit_company_id ON audit_logs (company_id);
CREATE INDEX idx_audit_user_id    ON audit_logs (user_id);
CREATE INDEX idx_audit_table_name ON audit_logs (table_name);

-- ── 21. devices ───────────────────────────────────────────────────────────────
CREATE TABLE devices (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  department_id     INTEGER NULL REFERENCES departments (id) ON DELETE SET NULL,
  name              VARCHAR(100) NOT NULL,
  serial_number     VARCHAR(80)  NOT NULL,
  location          VARCHAR(150) NULL,
  ip_address        VARCHAR(255) NULL,
  firmware_version  VARCHAR(30)  NULL,
  type              device_type_t NOT NULL DEFAULT 'FINGERPRINT',
  mode              device_mode_t NOT NULL DEFAULT 'ATTENDANCE',
  status            device_status_t NOT NULL DEFAULT 'ACTIVE',
  api_key           VARCHAR(64)  NOT NULL,
  last_sync         TIMESTAMP WITHOUT TIME ZONE NULL,
  created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_devices_serial UNIQUE (company_id, serial_number)
);

CREATE INDEX idx_devices_company_id    ON devices (company_id);
CREATE INDEX idx_devices_department_id ON devices (department_id);

-- ── 22. device_logs ───────────────────────────────────────────────────────────
CREATE TABLE device_logs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  device_id         INTEGER NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
  employee_id       INTEGER NULL REFERENCES employees (id) ON DELETE SET NULL,
  card_number       VARCHAR(80) NOT NULL,
  event_type        device_event_t NOT NULL DEFAULT 'CHECK_IN',
  event_time        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  raw_payload       JSONB NULL,
  is_duplicate      SMALLINT NOT NULL DEFAULT 0 CHECK (is_duplicate IN (0,1)),
  is_verify_only    SMALLINT NOT NULL DEFAULT 0 CHECK (is_verify_only IN (0,1)),
  processed         SMALLINT NOT NULL DEFAULT 0 CHECK (processed IN (0,1)),
  is_surprise       SMALLINT NOT NULL DEFAULT 0 CHECK (is_surprise IN (0,1)),
  surprise_event_id INTEGER NULL,
  created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  CONSTRAINT uq_device_log_dedup UNIQUE (device_id, card_number, event_type, event_time)
);

CREATE INDEX idx_dlog_company_id   ON device_logs (company_id);
CREATE INDEX idx_dlog_device_id    ON device_logs (device_id);
CREATE INDEX idx_dlog_employee_id  ON device_logs (employee_id);
CREATE INDEX idx_dlog_event_time   ON device_logs (event_time);
CREATE INDEX idx_dlog_processed    ON device_logs (processed);

-- ── 23. surprise_attendance_events ───────────────────────────────────────────
CREATE TABLE surprise_attendance_events (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id         INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
  title              VARCHAR(150) NOT NULL DEFAULT 'Surprise attendance check',
  message            TEXT NULL,
  starts_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  ends_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  duration_minutes   INTEGER NOT NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_by         INTEGER NULL REFERENCES users (id) ON DELETE SET NULL,
  created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_sae_company_id ON surprise_attendance_events (company_id);
CREATE INDEX idx_sae_status     ON surprise_attendance_events (status);

ALTER TABLE attendance
  ADD CONSTRAINT fk_attendance_surprise_event
  FOREIGN KEY (surprise_event_id) REFERENCES surprise_attendance_events (id) ON DELETE SET NULL;

ALTER TABLE device_logs
  ADD CONSTRAINT fk_device_logs_surprise_event
  FOREIGN KEY (surprise_event_id) REFERENCES surprise_attendance_events (id) ON DELETE SET NULL;

-- ── Supabase: enable RLS later if exposing PostgREST; backend uses service role ──
-- ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
